### ISSUE TITLE
Error when trying to Run the Job using tElasticsearchIndex

### ISSUE THREAD

**Issue by anooppa** [sylentprayer/Talend-Components#9]
![telasticsearch](https://cloud.githubusercontent.com/assets/14108185/11036443/9f758e48-871e-11e5-9e6a-d3bb432c0516.png)
Hi, I installed as per the documentation in Git. Got the tElasticsearch components in the palette. Created a new Job. Dragged in a DelimitedFileInput. As the output added tElasticsearchIndex.

I'm getting the following error when  iI run the Job:
```
Starting job Rest at 19:43 09/11/2015.

[statistics] connecting to socket on port 3349
[statistics] connected
Exception in thread "main" java.lang.Error: Unresolved compilation problems: 
	org.elasticsearch.common.settings.ImmutableSettings cannot be resolved to a type
	The constructor TransportClient(Settings) is undefined
	The constructor InetSocketTransportAddress(String, Integer) is undefined

	at local_project.rest_0_1.Rest.tFileInputDelimited_1Process(Rest.java:540)
	at local_project.rest_0_1.Rest.runJobInTOS(Rest.java:1083)
	at local_project.rest_0_1.Rest.main(Rest.java:940)
Job Rest ended at 19:43 09/11/2015. [exit code=0]
```
Following is the Elasticsever spec:
```
![telasticsearch](https://cloud.githubusercontent.com/assets/14108185/11036403/66ed31e8-871e-11e5-9285-fcd52f2a23d4.png)

{
  "name" : "Meteorite",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "2.0.0",
    "build_hash" : "de54438d6af8f9340d50c5c786151783ce7d6be5",
    "build_timestamp" : "2015-10-22T08:09:48Z",
    "build_snapshot" : false,
    "lucene_version" : "5.2.1"
  },
  "tagline" : "You Know, for Search"
}
```

**Comment by pklalitjha** [comment]
I think ES 2.0 has changed the API and constructor signature changed. Soo, I will fix and update exchange.

**Comment by sylentprayer** [comment]
ES 2.x support added to component version 1.0.4 and uploaded to Talend exchange (pending for approval). Also comitted code to tElasticsearchIndex project in github repo.

See updated tutorial http://spring-webservice-2-step-by-step.blogspot.in/2014/01/talend-elasticsearch-indexing-tutorial.html

**Comment by ghost** [comment]
Hi, 
Followed the new changes. But, hit with the following error.

```
Starting job SampleJob at 20:05 16/11/2015.

[statistics] connecting to socket on port 3746
[statistics] connected
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/collect/ImmutableMap
    at test.SampleJob_1_0.SampleJob.tFileInputDelimited_1Process(SampleJob.java:543)
    at test.SampleJob_1_0.SampleJob.runJobInTOS(SampleJob.java:1091)
    at test.SampleJob_1_0.SampleJob.main(SampleJob.java:948)
Caused by: java.lang.ClassNotFoundException: com.google.common.collect.ImmutableMap
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 3 more
[statistics] disconnected
Job SampleJob ended at 20:05 16/11/2015. [exit code=1]
```

**Comment by jankenr** [comment]
Hi there,

I just pulled the code from github and tested it in my Talend project. 
I still get an error:
**Caused by: java.lang.ClassNotFoundException: com.google.common.collect.ImmutableMap**
at java.net.URLClassLoader.findClass(Unknown Source)
at java.lang.ClassLoader.loadClass(Unknown Source)
at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
at java.lang.ClassLoader.loadClass(Unknown Source)
... 3 more

I have reloaded the correct component and used the right elastisearch.jar and lucene.jar:
- _elasticsearch-2.0.0.jar_
- _lucene-core-5.2.1.jar_

Did you test it yourself? And what were your outcomes?

Best regards,
Roel﻿

**Comment by jankenr** [comment]
I added the libraries (from the ElasticSearch 2.0 /lib directory) as mentioned in the Notes but still get the ImmutableMap error. I am a relative newby at Java.

This is the screenshot from my project
![talend_elasticsearch_2_0_error](https://cloud.githubusercontent.com/assets/9418563/11241086/0a40d8a6-8df8-11e5-9942-324bcb6abccc.png)

I hope you can help me...

Best regards,
Roel

**Comment by MadGhigno** [comment]
I tried to test the tElasticSearchIndex component with elasticsearch 2.2 but I encountered some problems. See my screenshot below.

![2016-02-24 1](https://cloud.githubusercontent.com/assets/6585247/13296185/8da62eb8-db2c-11e5-8181-1067a4183d71.png)

It worked fine and smooth with version 1.7.5 then we installed a new talend version and added the tElastiSearcIndex component as described here: [http://spring-webservice-2-step-by-step.blogspot.it/2014/01/talend-elasticsearch-indexing-tutorial.html](url)

Is there anything we can check in order to make it work ?

On talend machine we have java version "1.7.0_51"
On elasticsearch server we have java version "1.7.0_95"

Thanks in advance.
Roberto

**Comment by YashoShetty** [comment]
Hi Guys,

Did you find the solution for the issue you are facing? I am facing the exact same issue especially the one "jankenr" is facing.

**Comment by cdubois54** [comment]
Hi,

Strangely, I have the same problem today (Talend Data Integration 6.0.1 with the server part installation)
But everything works fine a few weeks ago.

Today, it seems like the generated java code for my job is based on ElasticSearchV1 java classes (with ImmutableSettings java class) although I have indicated the good versions of the libraries (elasticsearch and lucene) in the 'Module' view.
I don't know how the java code is generated, but could it be a problem of competition between several jar in configuration\lib\java?

Thanks in advance.

**Comment by cdubois54** [comment]
I find a solution : I had multiple tElasticSearchIndex component in the 'plugins' directory.
I check all of them and one was in an old version (where tElasticsearchIndex_begin.javajet doesn't manage ES v2) . 
I cleaned all of this %¨µ£%  manually and everything works fine yet.

**Comment by ofostier** [comment]
Hi all,

After new install of TOS Big Data a have this error message :
Message détaillé: The constructor InetSocketTransportAddress(String, Integer) is undefined

But i don't understand the origin of it.

Any issue about that ?

Thx
